export const EVENT_HIDE_TAB_BAR = "EVENT_HIDE_TAB_BAR"
export const EVENT_SHOW_TAB_BAR = "EVENT_SHOW_TAB_BAR"
export const EVENT_LOGOUT = "EVENT_LOGOUT"
export const EVENT_APPOINTMENT_ADDED_TO_CALENDAR = "EVENT_APPOINTMENT_ADDED_TO_CALENDAR"
